module.exports = [
  '<div class="year card">',
    '<div class="info">',
      '<span class="year-title">Year {{year}}</span>',
      '<span class="year-weight">Worth %<input class=""></span>',
    '</div>',
    '<div class="modules">',
      '<div class="modules-label">',
        '<div class="pull-left">Module(s):</div>',
        '<div class="details">',
          '<div class="details-name pull-left">Name: not required</div>',
          '<div class="pull-right">Weight: default is 1</div>',
        '</div>',
      '</div>',
      '<div class="clear-fix"></div>',
    '</div>',
    '<button class="btn btn-outline btn-small">Add Module</button>',
    '<div class="results">',
      '<span>Average:',
        '<span class="avg box">0%</span>',
      '</span>',
      '<span class="pull-right">Weighted:',
        '<span class="weight box">0%</span>',
      '</span>',
    '</div>',
  '</div>'
].join('');